# Use Node.js 18 Alpine as base
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Install necessary build dependencies
RUN apk add --no-cache python3 make g++

# Copy package files and tsconfig
COPY package*.json tsconfig.json ./

# Copy scripts and data
COPY scripts ./scripts

COPY .db /app/.db

# Install dependencies
RUN npm ci 
RUN npm install --save-dev @types/mongoose

#----
#Stage 2

FROM node:18-slim

WORKDIR /app

COPY --from=builder /app/package*.json ./

RUN npm install --omit=optional

# Copy package files, tsconfig, scripts and data
COPY --from=builder /app/tsconfig.json ./
COPY --from=builder /app/scripts/ ./scripts 
COPY --from=builder /app/.db ./.db


# Set environment variables
ENV NODE_ENV=development

# Command to run migration
CMD ["npx", "ts-node", "--project", "scripts/tsconfig.json", "scripts/migrate-data.ts"]
